### PR TITLE
Fixes lots of issues

### LINKED ISSUE #2322: Evaporation Generator 1.19.2
Minecraft Version:  1.19.2

Forge Version:  43.2.8

Mod Version:  1.19.2-1.8.2

Single Player or Server:  Server

Describe problem (what you were doing; what happened; what should have happened):
After checking all recipes it shows that Liquid Magma can be turned into energy but I can't transfer it with fluid cable's and fluid hopper. What should I do ?

Log file link:

Video/images/gifs (direct upload or link):

### LINKED ISSUE #2341: Crushing Macerator allows items to be shift-clicked into output slots
Minecraft Version: 1.20.1

Forge Version: 1.20.1-forge-47.1.76

Mod Version: 1.12.4

Single Player or Server: SP

Describe problem (what you were doing; what happened; what should have happened):
As the title says, just shift-click stuff while in the CM GUI and if the input slot is full or a different item then the shift-clicked item will go into the output slots.

### LINKED ISSUE #2343: Crushing Macerator continues to operate and void items if full
Minecraft Version: 1.20.1

Forge Version: 47.1.76

Mod Version: 1.12.4

Single Player or Server: SP

Describe problem (what you were doing; what happened; what should have happened):
I was grinding up freshly mined prismarine and put a stack in the Crushing Macerator. It reached 64 prismarine items in the output slot, then continued to operate, voiding the blocks in the input slot (and the required power).

### LINKED ISSUE #2358: auto crafting machine duplicate glitch
Minecraft Version: 
1.19.2
Forge Version: 
1.19.2
Mod Version: 
Cyclic-1.19.2-1.8.2
Single Player or Server:
Server
Describe problem (what you were doing; what happened; what should have happened):
When i put gold to craft into gold block at 2 it started to add up to 23 then it instant become 12 then 3 and repeat and gold is still crafted it works with other 3x3 same materials,they are taken by barrel(Sophisticated Storage) with advected hopper upgrade

Log file link:

Video/images/gifs (direct upload or link):

### LINKED ISSUE #2383: HashMap memory leak
Minecraft Version: 1.19.2

Forge Version: 43.3.8

Mod Version: 1.8.2

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

On heavy modpacks, the recipe cache from UtilPackager seems to leak a lot of memory when reconnecting to a server. I can provide you my memory dump if you need it.

Log file link: none

Video/images/gifs (direct upload or link): 
image

### LINKED ISSUE #2403: gps card inside wireless transmitter disappearing
Minecraft Version:  1.19.2

Forge Version: 43.3.9

Mod Version: 1.8.4

Single Player or Server: both

Describe problem (what you were doing; what happened; what should have happened):
i was: inserting a gps card in the wireless transmitter, then proceeded to break the transmitter to move it somewhere else with the card still inside;
what happened: gps card disappeared;
what should have happened: either gps card getting saved inside inventory or dropped onto the ground

Log file link:
nothing got logged about this interaction

Video/images/gifs (direct upload or link): 

https://clips.twitch.tv/ArborealAntsyAirGuitarStoneLightning-lj1AUdmYTnZh6jxC

edit: also tested in sp with just cyclic loaded

### PR DESCRIPTION
**Pull request by PocketSizedWeeb**
JEI Changes:

- Fixes issue #2369
- Made the JEI category for the Melter more closely match the Melter's GUI
- Moved the JEI "Show Recipe" area for the machines line up with the progress bar
- Moved the JEI "Show Recipe" area for the generators line up with the generator name
- Every applicable JEI Category got an energy bar added to show max consumed/produced RF
- Every applicable JEI Category got a progress bar to show how long the machine will run for
- Edited the Melter category texture to add space for energy bar
- Possibly fixed #2383 by caching an instance of Minecraft instead of grabbing it when needed in the Packager's JEI Category

Dry Peat:

- Fixes issue #2399 by allowing water-logged blocks to hydrate peat

Solidifier/Melter:

- Fully fixes desync issue by making all of the processing server sided.

Crushing Macerator:

- Fixed #2343
- Fixed #2341 

Evaporation Generator:

- Removed tank tooltip from before it was rotated
- Fixes #2322 by implementing a workaround since the fluid portion of FluidTagIngredient was defaulting to empty which was not allowing tagged fluids in the generator

Auto Crafter:
- Fixed #2358 by checking input before processing
- Fixed an issue where the preview slot wasn't updating until the machine was processing a craft

Wireless Transmitter:
- Fixed #2403 by adding an onRemove method to the transmitter that drops the gps card

@Lothrazar I also have a working JEI Category for the Combustion Generator and Devouring Generator if you want me to make a pull request for it.

### CODE REVIEW

File: src/main/java/com/lothrazar/cyclic/compat/jei/MelterRecipeCategory.java [hunk 1]
```diff
@@ -57,17 +70,18 @@ public RecipeType<RecipeMelter> getRecipeType() {
...
+    progress.renderHoveredToolTip(ms, (int) mouseX, (int) mouseY, recipe.getEnergy().getTicks());
   }
 
   @Override
   public void setRecipe(IRecipeLayoutBuilder builder, RecipeMelter recipe, IFocusGroup focuses) {
     builder.addSlot(RecipeIngredientRole.INPUT, 4, 19).addIngredients(recipe.at(0));
     builder.addSlot(RecipeIngredientRole.INPUT, 22, 19).addIngredients(recipe.at(1));
     List<FluidStack> matchingFluids = List.of(recipe.getRecipeFluid());
-    builder.addSlot(RecipeIngredientRole.OUTPUT, 140, 19).addIngredients(ForgeTypes.FLUID_STACK, matchingFluids);
+    builder.addSlot(RecipeIngredientRole.OUTPUT, 132, 19).addIngredients(ForgeTypes.FLUID_STACK, matchingFluids).setFluidRenderer(4000, false, 16, 16);
```
Comment (Lothrazar) [inline src/main/java/com/lothrazar/cyclic/compat/jei/MelterRecipeCategory.java:85]: sweet i never knew jei had a fluid renderer like this

File: src/main/java/com/lothrazar/cyclic/compat/jei/MelterRecipeCategory.java [hunk 2]
```diff
@@ -29,10 +34,18 @@ public class MelterRecipeCategory implements IRecipeCategory<RecipeMelter> {
...
   private IDrawable icon;
+  private Font font;
+  private EnergyBar bar;
+  private TexturedProgress progress;
 
   public MelterRecipeCategory(IGuiHelper helper) {
+	font = Minecraft.getInstance().font;
     gui = helper.drawableBuilder(new ResourceLocation(ModCyclic.MODID, "textures/jei/melter_recipe.png"), 0, 0, 169, 69).setTextureSize(169, 69).build();
     icon = helper.createDrawableIngredient(VanillaTypes.ITEM_STACK, new ItemStack(BlockRegistry.MELTER.get()));
+    bar = new EnergyBar(font, TileSolidifier.MAX);
```
Comment (Lothrazar) [inline src/main/java/com/lothrazar/cyclic/compat/jei/MelterRecipeCategory.java:45]: ha why didnt i think of that. i made the bars module but never thought to re use them into the jei component. smart

File: src/main/java/com/lothrazar/cyclic/block/wireless/redstone/BlockWirelessTransmit.java [hunk 3]
```diff
@@ -44,4 +45,18 @@ public <T extends BlockEntity> BlockEntityTicker<T> getTicker(Level world, Block
   protected void createBlockStateDefinition(StateDefinition.Builder<Block, BlockState> builder) {
     builder.add(POWERED);
   }
+  
+  @Override // was onReplaced
+  public void onRemove(BlockState state, Level worldIn, BlockPos pos, BlockState newState, boolean isMoving) {
```
Comment (Lothrazar) [inline src/main/java/com/lothrazar/cyclic/block/wireless/redstone/BlockWirelessTransmit.java:50]: good catch

File: src/main/java/com/lothrazar/cyclic/block/solidifier/TileSolidifier.java [hunk 4]
```diff
@@ -71,6 +71,10 @@ public void tick() {
       this.timer = 0;
       return;
     }
+    //Fixes sync issue entirely
+    if(level.isClientSide()) return;
+    //Checks if there is space in the output slot
+    if(this.outputSlots.getStackInSlot(0).getCount() > 64 - currentRecipe.getResultItem(level.registryAccess()).getCount()) return;
```
Comment (Lothrazar) [inline src/main/java/com/lothrazar/cyclic/block/solidifier/TileSolidifier.java:77]: can we assume the max is always 64? what if its an ender pearl and 16 is the max. well we can check that later, still a good fix

File: src/main/java/com/lothrazar/cyclic/block/melter/TileMelter.java [hunk 5]
```diff
@@ -67,6 +67,8 @@ public void tick() {
     if (currentRecipe == null) {
       return;
     }
+    //Fixes sync issue entirely
```
Comment (Lothrazar) [inline src/main/java/com/lothrazar/cyclic/block/melter/TileMelter.java:70]: noice

File: src/main/java/com/lothrazar/cyclic/block/crusher/TileCrusher.java [hunk 6]
```diff
@@ -111,6 +111,14 @@ public void tick() {
     if (level.isClientSide) {
       return;
     }
+    if (currentRecipe == null) {
+        this.findMatchingRecipe();
+        return;
+    }
+    //Checks if there is space in the output slots before processing
+    if(outputSlots.getStackInSlot(0).getCount() > 64 - currentRecipe.getResultItem(level.registryAccess()).copy().getCount()) return;
```
Comment (Lothrazar) [inline src/main/java/com/lothrazar/cyclic/block/crusher/TileCrusher.java:119]: fix looks good!  the hardcoded 64 can be an issue, for example if i have a recipe that outputs 3 ender pearls, that has a max stack size of 16 so it has that issue.  i can change it later you just do it something like this
 ``` 
var result = currentRecipe.getResultItem(level.registryAccess()).copy();
var max = result.getMaxStackSize();
```

File: src/main/java/com/lothrazar/cyclic/block/crafter/TileCrafter.java [hunk 7]
```diff
@@ -211,6 +213,35 @@ private boolean hasFreeSpace(IItemHandler inv, ItemStack output) {
...
+	  List<ItemStack> inputStacks = new ArrayList<ItemStack>();
+	  List<ItemStack> gridStacks = new ArrayList<ItemStack>();
+	  for(int i = 0; i < inv.getSlots(); i++) {
+		  inputStacks.add(inv.getStackInSlot(i).copy());
+	  }
+	  for(int i = 0; i < gridHandler.getSlots(); i++) {
+		  gridStacks.add(gridHandler.getStackInSlot(i).copy());
+	  }
+	  for(ItemStack stack : inputStacks) {
+		  List<ItemStack> lolbit = new ArrayList<ItemStack>();
```
Comment (Lothrazar) [inline src/main/java/com/lothrazar/cyclic/block/crafter/TileCrafter.java:228]: aha so lolbit are the matches so we know what to clear out when we are removingall i got it. works in my testing 👍

**Review by Lothrazar — APPROVED** [review]
great work and thanks for your patience! i tested everything and reviewed all the code and the fixes look good, they address the issues as stated

**Comment by Lothrazar** [comment]
And yeah for "I also have a working JEI Category for the Combustion Generator and Devouring Generator if you want me to make a pull request for it." yeah i would merge it. i figured people would just know what is edible or what is furnace fuel (coal and lava) but it would be nice for lots of players
