### PR TITLE
[1.16] Fix compatibility with Repurposed Structures mod

### LINKED ISSUE #1517: Solid Ender Eye not working
**Minecraft Version**: 1.16.3

**Forge Version**: 34.1.15

**Mod Version**:  0.8.0

**Single Player or Server**: Server

**Describe problem (what you were doing; what happened; what should have happened)**:

Solid Ender Eye not throwing Ender Eyes at all, literally not working.

### PR DESCRIPTION
**Pull request by trunksbomb**
Closes #1517. See comments there and https://github.com/TelepathicGrunt/RepurposedStructures/issues/38 here for more info.

tl;dr: RS replaces vanilla Stronghold so we have to detect presence of that mod and detect its version of Strongholds instead when present.

Also added the ability for Solid Ender Eye to find Nether Strongholds from RS Mod.

### CODE REVIEW

File: src/main/java/com/lothrazar/cyclic/item/endereye/ItemEnderEyeReuse.java [hunk 1]
```diff
@@ -2,54 +2,99 @@
...
 
   public ItemEnderEyeReuse(Properties properties) {
     super(properties.maxDamage(256));
   }
 
+  //compat with Repurposed Structures Mod see #1517
+  private static final String RS_MODID = "repurposed_structures";
+  private static final String RS_STRONGHOLD_ID = "stronghold_stonebrick";
+  private static final String RS_NETHER_STRONGHOLD_ID = "stronghold_nether";
+  private static final ResourceLocation RS_RESOURCE_LOCATION = new ResourceLocation(RS_MODID, RS_STRONGHOLD_ID);
```
Comment (Lothrazar) [inline src/main/java/com/lothrazar/cyclic/item/endereye/ItemEnderEyeReuse.java:35]: oh nice, thats easier than i expected. means we dont have to import any of the mods code
